-- Sequences for Chat and Offers
CREATE SEQUENCE MESSAGES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OFFERS_SEQ START WITH 1 INCREMENT BY 1;

-- Table: MESSAGES
CREATE TABLE MESSAGES (
    ID NUMBER DEFAULT MESSAGES_SEQ.NEXTVAL PRIMARY KEY,
    LISTING_ID NUMBER NOT NULL,
    SENDER_ID NUMBER NOT NULL,
    RECEIVER_ID NUMBER NOT NULL,
    CONTENT CLOB NOT NULL,
    IS_READ NUMBER(1) DEFAULT 0, -- 0 for Unread, 1 for Read
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MSG_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSG_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSG_RECEIVER FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table: OFFERS
CREATE TABLE OFFERS (
    ID NUMBER DEFAULT OFFERS_SEQ.NEXTVAL PRIMARY KEY,
    LISTING_ID NUMBER NOT NULL,
    BUYER_ID NUMBER NOT NULL,
    SELLER_ID NUMBER NOT NULL,
    OFFER_PRICE NUMBER(10, 2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, ACCEPTED, REJECTED
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OFFER_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_OFFER_BUYER FOREIGN KEY (BUYER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_OFFER_SELLER FOREIGN KEY (SELLER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Index for faster chat retrieval
CREATE INDEX IDX_CHAT_USERS ON MESSAGES(SENDER_ID, RECEIVER_ID, LISTING_ID);
