-- Drop existing tables if they exist (ordered by dependencies)
DROP TABLE IF EXISTS WISHLIST CASCADE;
DROP TABLE IF EXISTS IMAGES CASCADE;
DROP TABLE IF EXISTS LISTINGS CASCADE;
DROP TABLE IF EXISTS CATEGORIES CASCADE;

-- Table: CATEGORIES
CREATE TABLE CATEGORIES (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE
);

-- Table: LISTINGS
CREATE TABLE LISTINGS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE NUMERIC(10, 2) NOT NULL,
    LOCATION VARCHAR(255),
    ITEM_CONDITION VARCHAR(50),
    CATEGORY_ID INTEGER,
    SELLER_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LISTING_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    CONSTRAINT FK_LISTING_SELLER FOREIGN KEY (SELLER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table: IMAGES
CREATE TABLE IMAGES (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LISTING_ID INTEGER NOT NULL,
    IMAGE_URL VARCHAR(500) NOT NULL,
    CONSTRAINT FK_IMAGE_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE
);

-- Table: WISHLIST
CREATE TABLE WISHLIST (
    USER_ID INTEGER NOT NULL,
    LISTING_ID INTEGER NOT NULL,
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, LISTING_ID),
    CONSTRAINT FK_WISHLIST_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WISHLIST_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE
);