-- Drop existing tables if they exist (ordered by dependencies)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE WISHLIST CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE IMAGES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE LISTINGS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP SEQUENCE LISTINGS_SEQ';
   EXECUTE IMMEDIATE 'DROP SEQUENCE CATEGORIES_SEQ';
   EXECUTE IMMEDIATE 'DROP SEQUENCE IMAGES_SEQ';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 AND SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

-- Sequences
CREATE SEQUENCE CATEGORIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LISTINGS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IMAGES_SEQ START WITH 1 INCREMENT BY 1;

-- Table: CATEGORIES
CREATE TABLE CATEGORIES (
    ID NUMBER DEFAULT CATEGORIES_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL UNIQUE
);

-- Table: LISTINGS
CREATE TABLE LISTINGS (
    ID NUMBER DEFAULT LISTINGS_SEQ.NEXTVAL PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    DESCRIPTION CLOB,
    PRICE NUMBER(10, 2) NOT NULL,
    LOCATION VARCHAR2(255),
    CATEGORY_ID NUMBER,
    SELLER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LISTING_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    CONSTRAINT FK_LISTING_SELLER FOREIGN KEY (SELLER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Table: IMAGES
CREATE TABLE IMAGES (
    ID NUMBER DEFAULT IMAGES_SEQ.NEXTVAL PRIMARY KEY,
    LISTING_ID NUMBER NOT NULL,
    IMAGE_URL VARCHAR2(500) NOT NULL,
    CONSTRAINT FK_IMAGE_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE
);

-- Table: WISHLIST
CREATE TABLE WISHLIST (
    USER_ID NUMBER NOT NULL,
    LISTING_ID NUMBER NOT NULL,
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, LISTING_ID),
    CONSTRAINT FK_WISHLIST_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WISHLIST_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE
);
