
-- Suppress output for missing table drops implicitly
SET SERVEROUTPUT ON;

-- 1. USERS table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'USERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE TABLE USERS (
        ID NUMBER DEFAULT USERS_SEQ.NEXTVAL PRIMARY KEY,
        USERNAME VARCHAR2(50) NOT NULL UNIQUE,
        EMAIL VARCHAR2(100) NOT NULL UNIQUE,
        PASSWORD VARCHAR2(255) NOT NULL,
        PHONE VARCHAR2(20),
        PROFILE_PICTURE VARCHAR2(500),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )';
    DBMS_OUTPUT.PUT_LINE('Created USERS table.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('USERS table already exists.');
  END IF;
END;
/

-- 2. CATEGORIES table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'CATEGORIES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE CATEGORIES_SEQ START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE TABLE CATEGORIES (
        ID NUMBER DEFAULT CATEGORIES_SEQ.NEXTVAL PRIMARY KEY,
        NAME VARCHAR2(100) NOT NULL UNIQUE
    )';
    DBMS_OUTPUT.PUT_LINE('Created CATEGORIES table.');
  END IF;
END;
/

-- 3. Patch LISTINGS Table
DECLARE
    column_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(column_exists, -01430);
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE LISTINGS ADD LOCATION VARCHAR2(255)';
    EXECUTE IMMEDIATE 'ALTER TABLE LISTINGS ADD ITEM_CONDITION VARCHAR2(50)';
    EXECUTE IMMEDIATE 'ALTER TABLE LISTINGS ADD CATEGORY_ID NUMBER';
    EXECUTE IMMEDIATE 'ALTER TABLE LISTINGS ADD SELLER_ID NUMBER'; 
    EXECUTE IMMEDIATE 'ALTER TABLE LISTINGS ADD CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
    DBMS_OUTPUT.PUT_LINE('Altered LISTINGS table.');
EXCEPTION
    WHEN column_exists THEN
        DBMS_OUTPUT.PUT_LINE('Some columns already exist in LISTINGS.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error altering LISTINGS: ' || SQLERRM);
END;
/

-- 4. IMAGES table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'IMAGES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE IMAGES_SEQ START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE TABLE IMAGES (
        ID NUMBER DEFAULT IMAGES_SEQ.NEXTVAL PRIMARY KEY,
        LISTING_ID NUMBER NOT NULL,
        IMAGE_URL VARCHAR2(2000) NOT NULL,
        CONSTRAINT FK_IMAGE_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created IMAGES table.');
  END IF;
END;
/

-- 5. WISHLIST table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'WISHLIST';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE WISHLIST (
        USER_ID NUMBER NOT NULL,
        LISTING_ID NUMBER NOT NULL,
        ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (USER_ID, LISTING_ID),
        CONSTRAINT FK_WISHLIST_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_WISHLIST_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created WISHLIST table.');
  END IF;
END;
/

-- 6. MESSAGES table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'MESSAGES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE MESSAGES_SEQ START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE TABLE MESSAGES (
        ID NUMBER DEFAULT MESSAGES_SEQ.NEXTVAL PRIMARY KEY,
        LISTING_ID NUMBER NOT NULL,
        SENDER_ID NUMBER NOT NULL,
        RECEIVER_ID NUMBER NOT NULL,
        CONTENT CLOB NOT NULL,
        IS_READ NUMBER(1) DEFAULT 0,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT FK_MSG_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_MSG_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_MSG_RECEIVER FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CHAT_USERS ON MESSAGES(SENDER_ID, RECEIVER_ID, LISTING_ID)';
    DBMS_OUTPUT.PUT_LINE('Created MESSAGES table.');
  END IF;
END;
/

-- 7. OFFERS table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'OFFERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE OFFERS_SEQ START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE TABLE OFFERS (
        ID NUMBER DEFAULT OFFERS_SEQ.NEXTVAL PRIMARY KEY,
        LISTING_ID NUMBER NOT NULL,
        BUYER_ID NUMBER NOT NULL,
        SELLER_ID NUMBER NOT NULL,
        OFFER_PRICE NUMBER(10, 2) NOT NULL,
        STATUS VARCHAR2(20) DEFAULT ''PENDING'',
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT FK_OFFER_LISTING FOREIGN KEY (LISTING_ID) REFERENCES LISTINGS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_OFFER_BUYER FOREIGN KEY (BUYER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
        CONSTRAINT FK_OFFER_SELLER FOREIGN KEY (SELLER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created OFFERS table.');
  END IF;
END;
/

COMMIT;
EXIT;
