-- Increase IMAGE_URL column length for IMAGES table
ALTER TABLE IMAGES MODIFY IMAGE_URL VARCHAR2(2000);
-- Create Sequence for USERS table
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

-- Create USERS table
CREATE TABLE USERS (
    ID NUMBER DEFAULT USERS_SEQ.NEXTVAL PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
